<html>
    <head>
        <meta charset="utf-8"/>
        <title>AppGym</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="css/estilos.css">
    </head>
    <body>
        <h1>La Web de Chicho</h1>
        <div>El poder esta en mi!</div>
        <div>JAJA Locote</div>
        <?php if (isset($name)) : ?>
            <h2>Hello <?= htmlspecialchars($name); ?>!</h2>
        <?php else: ?>
            <p>Try <a href="/SlimFramework">/SlimFramework</a>
        <?php endif; ?>
    </body>
</html>
